// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahewugbsgddrvggsllmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoZXd1Z2JzZ2RkcnZnZ3NsbG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5OTc2MTcsImV4cCI6MjA4ODU3MzYxN30.pG5jYEn3Ydh36WjBEeRlWHAk2P1m8rhIRxzGV8GJ734";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});